allowBuilds:
  '@prisma/engines': true
  bufferutil: true
  esbuild: set this to true or false
  keccak: true
  prisma: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

packages:
  - '.'
